### ISSUE TITLE
illegal reflective access operation

### ISSUE THREAD

**Issue by faust347** [updown2/MooneyFaceGenerator#1]
sudo java -Xmx2g -jar mooney-generator.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/user/Mooney/mooney-generator.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5LibraryException
	at ncsa.hdf.hdf5lib.H5._H5Fopen(Native Method)
	at ncsa.hdf.hdf5lib.H5.H5Fopen(H5.java:2546)
	at ncsa.hdf.object.h5.H5File.open(H5File.java:1943)
	at ncsa.hdf.object.h5.H5File.open(H5File.java:1869)
	at ncsa.hdf.object.h5.H5File.open(H5File.java:949)
	at scalismo.io.HDF5Utils$$anonfun$openFile$1.apply(HDF5Utils.scala:337)
	at scalismo.io.HDF5Utils$$anonfun$openFile$1.apply(HDF5Utils.scala:326)
	at scala.util.Try$.apply(Try.scala:192)
	at scalismo.io.HDF5Utils$.openFile(HDF5Utils.scala:326)
	at scalismo.io.HDF5Utils$.openFileForReading(HDF5Utils.scala:343)
	at scalismo.faces.io.MoMoIO$$anonfun$read$2.apply(MoMoIO.scala:95)
	at scalismo.faces.io.MoMoIO$$anonfun$read$2.apply(MoMoIO.scala:95)
	at scalismo.faces.utils.ResourceManagement$.usingTry(ResourceManagement.scala:60)
	at scalismo.faces.io.MoMoIO$.read(MoMoIO.scala:95)
	at faces.apps.MooneyFaceGeneratorGUI.<init>(MooneyFaceGenerator.scala:82)
	at faces.apps.MooneyFaceGenerator$$anonfun$26.apply(MooneyFaceGenerator.scala:46)
	at faces.apps.MooneyFaceGenerator$$anonfun$26.apply(MooneyFaceGenerator.scala:46)
	at scala.Option.map(Option.scala:146)
	at faces.apps.MooneyFaceGenerator$.delayedEndpoint$faces$apps$MooneyFaceGenerator$1(MooneyFaceGenerator.scala:46)
	at faces.apps.MooneyFaceGenerator$delayedInit$body.apply(MooneyFaceGenerator.scala:41)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at faces.apps.MooneyFaceGenerator$.main(MooneyFaceGenerator.scala:41)
	at faces.apps.MooneyFaceGenerator.main(MooneyFaceGenerator.scala)

**Comment by BernhardEgger** [comment]
Hi,

you need to install java open gl (jogl).
jogl is provided with some java distributions, for others you have to install it separately

Best
Bernhard
