### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Kracozebr** [updown2/MooneyFaceGenerator#2]
I'm trying to run the  mooney generator from Ubuntu:
```
java -Xmx2g -jar mooney-generator.jar
```

And got the next exception:
```
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
	at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
	at faces.apps.MooneyFaceGeneratorGUI.<init>(MooneyFaceGenerator.scala:104)
	at faces.apps.MooneyFaceGenerator$$anonfun$26.apply(MooneyFaceGenerator.scala:46)
	at faces.apps.MooneyFaceGenerator$$anonfun$26.apply(MooneyFaceGenerator.scala:46)
	at scala.Option.map(Option.scala:146)
	at faces.apps.MooneyFaceGenerator$.delayedEndpoint$faces$apps$MooneyFaceGenerator$1(MooneyFaceGenerator.scala:46)
	at faces.apps.MooneyFaceGenerator$delayedInit$body.apply(MooneyFaceGenerator.scala:41)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at faces.apps.MooneyFaceGenerator$.main(MooneyFaceGenerator.scala:41)
	at faces.apps.MooneyFaceGenerator.main(MooneyFaceGenerator.scala)
```
How to troubleshoot this issue?

**Comment by Kracozebr** [comment]
My bad did not put Basel Illumination Prior under data
